# tasks/attack_cycle_tasks.yml
---
- name: "Calculate attack duration based on intensity"
  set_fact:
    attack_duration: >-
      {% if intensity == 'high' %}
      {{ 900 + (1800 - 900 + 1) | random }}
      {% elif intensity == 'mid' %}
      {{ 600 + (900 - 600 + 1) | random }}
      {% else %}
      {{ 300 + (600 - 300 + 1) | random }}
      {% endif %}

- name: "Log attack duration"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Setting attack duration to {{ attack_duration }} seconds for this cycle"
    insertafter: EOF
  become: true

- name: "Copy attack script"
  copy:
    src: "{{ scripts_dir }}/syn_flood.sh"
    dest: "/home/cybears/ddos_scripts/attack.sh"
    mode: '0755'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"

- name: "Ensure script execution rights"
  file:
    path: "/home/cybears/ddos_scripts/attack.sh"
    mode: '0755'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"

- name: "Log attack start"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Starting attack on {{ item }} at: {{ '%Y-%m-%d %H:%M:%S' | strftime }}, planned duration: {{ attack_duration }} seconds"
    insertafter: EOF
  with_items: "{{ attacker_hosts }}"
  become: true

- name: "Execute attack script with duration"
  shell: |
    cd /home/cybears/ddos_scripts
    ./attack.sh {{ attack_duration|int }} 2>&1 | tee attack.log
  async: "{{ (attack_duration|int) + 300 }}"
  poll: -1
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"
  register: attack_result
  become: true
  become_user: cybears

- name: "Log attack cycle completion"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Attack cycle completed at: {{ '%Y-%m-%d %H:%M:%S' | strftime }}"
    insertafter: EOF
  become: true