# tasks/packet_capture.yml
---
- name: "Ensure PCAP directory exists with proper permissions"
  file:
    path: "/var/log/pcap"
    state: directory
    mode: '0755'
    owner: root
    group: root
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true

- name: "Generate PCAP filename"
  set_fact:
    pcap_filename: "ddos_{{ intensity }}_{{ cycle_timestamp }}_{{ attacker_count }}-attackers.pcap"

- name: "Check tcpdump installation"
  command: "which tcpdump"
  register: tcpdump_check
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  ignore_errors: true

- name: "Debug tcpdump installation"
  debug:
    msg: "tcpdump binary location: {{ tcpdump_check.stdout }}"
  when: tcpdump_check.rc == 0

- name: "Check interface list"
  shell: "ip link show | grep -v 'link\\|loopback' | cut -d: -f2 | tr -d ' '"
  register: interface_list
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true

- name: "Debug available interfaces"
  debug:
    msg: "Available interfaces: {{ interface_list.stdout_lines }}"

- name: "Start tcpdump with verbose output"
  shell: |
    tcpdump -i any -w /var/log/pcap/{{ pcap_filename }} -v 2>/var/log/pcap/tcpdump_error.log &
    echo $! > /var/log/pcap/tcpdump.pid
  async: 3600
  poll: 0
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  register: tcpdump_job

- name: "Check tcpdump error log"
  shell: "cat /var/log/pcap/tcpdump_error.log"
  register: tcpdump_errors
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  ignore_errors: true

- name: "Debug tcpdump errors"
  debug:
    msg: "Tcpdump errors: {{ tcpdump_errors.stdout }}"

- name: "Verify tcpdump is running"
  shell: "pgrep tcpdump"
  register: tcpdump_check
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  retries: 3
  delay: 2
  until: tcpdump_check.rc == 0

- name: "Record capture start"
  lineinfile:
    path: "{{ log_dir }}/ddos_sim_{{ cycle_timestamp }}.log"
    line: "Packet capture started at {{ '%Y-%m-%d %H:%M:%S' | strftime }} - File: {{ pcap_filename }} (Job ID: {{ tcpdump_job.ansible_job_id }})"
    insertafter: EOF
  become: true