# tasks/packet_capture.yml
---
- name: "Ensure PCAP directory exists with correct permissions"
  file:
    path: "/var/log/pcap"
    state: directory
    mode: '0755'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"
  become: true

- name: "Set proper permissions for error log"
  file:
    path: "/var/log/pcap/tcpdump_error.log"
    state: touch
    mode: '0644'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"
  become: true

- name: "Generate PCAP filename for each server"
  set_fact:
    pcap_filename: "ddos_{{ simulation_start }}_{{ intensity }}_{{ cycle_timestamp }}_{{ ansible_host }}.pcap"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"

- name: "Start tcpdump on each web server"
  shell: |
    nohup tcpdump -i any -s 0 -n -B 4096 \
    'tcp and (port 80 or port 443) and (tcp[tcpflags] & (tcp-syn|tcp-ack|tcp-push|tcp-rst) != 0)' \
    -w '/var/log/pcap/{{ pcap_filename }}' \
    -v 2>/var/log/pcap/tcpdump_error.log &
    echo $! > /var/log/pcap/tcpdump.pid
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"
  become: true
  async: 86400
  poll: 0

- name: "Wait for tcpdump to start"
  pause:
    seconds: 2

- name: "Check tcpdump error log"
  shell: "cat /var/log/pcap/tcpdump_error.log"
  register: tcpdump_errors
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"
  become: true
  ignore_errors: true

- name: "Verify tcpdump is running"
  shell: "ps aux | grep -v grep | grep tcpdump"
  register: tcpdump_check
  delegate_to: "{{ item }}"
  with_items: "{{ groups['webservers'] }}"
  become: true
  retries: 3
  delay: 2
  until: tcpdump_check.rc == 0

- name: "Record capture start"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Packet capture started at {{ '%Y-%m-%d %H:%M:%S' | strftime }} on {{ item }} - File: {{ pcap_filename }}"
    insertafter: EOF
  with_items: "{{ groups['webservers'] }}"
  become: true