# tasks/packet_capture.yml
---
- name: "Ensure PCAP directory exists with proper permissions"
  file:
    path: "/var/log/pcap"
    state: directory
    mode: '0755'
    owner: root
    group: root
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true

- name: "Generate PCAP filename"
  set_fact:
    pcap_filename: "ddos_{{ intensity }}_{{ cycle_timestamp }}_{{ attacker_count }}-attackers.pcap"

- name: "Start tcpdump"
  command: "tcpdump -i any -w /var/log/pcap/{{ pcap_filename }}"
  async: 3600
  poll: 0
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  register: tcpdump_job

- name: "Verify tcpdump is running"
  shell: "pgrep tcpdump"
  register: tcpdump_check
  delegate_to: "{{ groups['monitor'][0] }}"
  become: true
  retries: 3
  delay: 2
  until: tcpdump_check.rc == 0

- name: "Record capture start"
  lineinfile:
    path: "{{ log_dir }}/ddos_sim_{{ cycle_timestamp }}.log"
    line: "Packet capture started at {{ '%Y-%m-%d %H:%M:%S' | strftime }} - File: {{ pcap_filename }} (Job ID: {{ tcpdump_job.ansible_job_id }})"
    insertafter: EOF
  become: true