# tasks/role_assignment.yml
---
- name: "Get host information for grouping"
  set_fact:
    all_hosts: "{{ groups['subnet_a'] }}"
    cycle_timestamp: "{{ '%Y%m%d_%H%M%S' | strftime }}"
    total_hosts: "{{ groups['subnet_a'] | length | int }}"

- name: "Calculate attacker percentages and counts"
  set_fact:
    min_attackers: "{% if intensity == 'high' %}{{ (total_hosts|float * 0.65)|round|int }}{% elif intensity == 'mid' %}{{ (total_hosts|float * 0.35)|round|int }}{% elif intensity == 'low' %}{{ (total_hosts|float * 0.05)|round|int }}{% else %}0{% endif %}"
    max_attackers: "{% if intensity == 'high' %}{{ (total_hosts|float * 0.85)|round|int }}{% elif intensity == 'mid' %}{{ (total_hosts|float * 0.65)|round|int }}{% elif intensity == 'low' %}{{ (total_hosts|float * 0.35)|round|int }}{% else %}0{% endif %}"

- name: "Set final attacker count"
  set_fact:
    attacker_count: "{{ min_attackers|int + range(max_attackers|int - min_attackers|int)|random }}"

- name: "Calculate normal count"
  set_fact:
    normal_count: "{{ total_hosts|int - attacker_count|int }}"

- name: "Shuffle and assign roles"
  set_fact:
    shuffled_hosts: "{{ all_hosts | shuffle }}"

- name: "Split into attackers and normal hosts"
  set_fact:
    attacker_hosts: "{{ shuffled_hosts[:attacker_count|int] }}"
    normal_hosts: "{{ shuffled_hosts[attacker_count|int:] }}"

- name: "Log role assignments"
  copy:
    content: |
      =====================================
      Attack Cycle Start - {{ cycle_timestamp }}
      =====================================
      Intensity Level: {{ intensity }}
      Total Machines: {{ total_hosts }}
      Number of Attackers: {{ attacker_count }}
      Number of Normal Hosts: {{ normal_count }}

      =====================================
      Attacker Hosts ({{ attacker_count }})
      =====================================
      {% for host in attacker_hosts %}
      {{ host }}:
        IP: {{ hostvars[host]['ansible_host'] }}
      {% endfor %}

      =====================================
      Normal Hosts ({{ normal_count }})
      =====================================
      {% for host in normal_hosts %}
      {{ host }}:
        IP: {{ hostvars[host]['ansible_host'] }}
      {% endfor %}
    dest: "{{ log_dir }}/ddos_sim_{{ simulation_start }}_{{ cycle_timestamp }}.log"
    mode: '0644'
  become: true