# tasks/attack_cycle_tasks.yml
---
- name: "Calculate attack duration based on intensity"
  set_fact:
    attack_duration: >-
      {% if intensity == 'high' %}
      {{ 60 + (90 - 60 + 1) | random }}
      {% elif intensity == 'mid' %}
      {{ 30 + (60 - 30 + 1) | random }}
      {% elif intensity == 'low' %}
      {{ 15 + (30 - 15 + 1) | random }}
      {% else %}
      0
      {% endif %}


- name: "Set buffer time"
  set_fact:
    buffer_time: 300

- name: "Log attack duration"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Setting attack duration to {{ attack_duration }} seconds for this cycle"
    insertafter: EOF
  become: true

- name: "Copy attack script"
  copy:
    src: "{{ scripts_dir }}/syn_flood.sh"
    dest: "/home/cybears/ddos_scripts/attack.sh"
    mode: '0755'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"

- name: "Ensure script execution rights"
  file:
    path: "/home/cybears/ddos_scripts/attack.sh"
    mode: '0755'
    owner: cybears
    group: cybears
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"

- name: "Log attack start"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Starting attack on {{ item }} at: {{ '%Y-%m-%d %H:%M:%S' | strftime }}, planned duration: {{ attack_duration }} seconds"
    insertafter: EOF
  with_items: "{{ attacker_hosts }}"
  become: true

- name: "Execute attack script"
  shell: |
    cd /home/cybears/ddos_scripts
    ./attack.sh {{ attack_duration|int }} 2>&1 | tee attack.log
  async: "{{ attack_duration|int + buffer_time }}"
  poll: 0
  delegate_to: "{{ item }}"
  with_items: "{{ attacker_hosts }}"
  become: true
  become_user: cybears

- name: "Sleep for attack duration"
  wait_for:
    timeout: "{{ attack_duration|int }}"

- name: "Log attack cycle completion"
  lineinfile:
    path: "{{ log_dir }}/master_sim_{{ simulation_start }}.log"
    line: "Attack cycle completed at: {{ '%Y-%m-%d %H:%M:%S' | strftime }}"
    insertafter: EOF
  become: true